### ISSUE TITLE
Latest version published on npm is v10 - Will new versions be published?

### ISSUE THREAD

**Issue by afermon** [HNeukermans/ng2-signalr#187]
Hi, thanks for the library.

The latest version on npm for ng2-signalr is 10.1.0 but i see in the repository there are chnages to support Angular v11 and v12.

Will this version be published to npm?

On npm v10.1.0
```json
"peerDependencies": {
    "@angular/common": "^10.0.0",
    "@angular/core": "^10.0.0"
  },
```
On repository
```json
  "peerDependencies": {
    "@angular/common": ">=11.0.0",
    "@angular/core": ">=11.0.0"
  },
```

**Comment by Bykiev** [comment]
@HNeukermans, please, update npm package!

**Comment by henkkelder** [comment]
I created a fork at henkkelder/ng2-signalr that works for me.
Published it also https://www.npmjs.com/package/@henkkelder/ng2-signalr

**Comment by Bykiev** [comment]
@henkkelder, will you maintain it or it's a fork just for publishing updated npm version? Can you please publish npm package for angular 11 too?

**Comment by henkkelder** [comment]
@Bykiev Its just a fork to get it working for Angular 12+. 

The publish to npmjs was needed because I was unable to import the package directly from github. 
Doing local builds you can import it from local system e.g. npm install \workspace\ng2-signalr\dist\ng2-signalr. But this doesn't work when using a clould build engine like I do.

You could make your own fork and change the dependencies in the package.json that is in de projects\ng2-signalr folder.

Alternatively, upgrade your project to Angular12?
