### ISSUE TITLE
[Enhancement] Get SignalRConnection without actually starting it

### ISSUE THREAD

**Issue by spacepope** [HNeukermans/ng2-signalr#29]
Hi there,

at first thanks for this well structured library.
In SignalR it is common usage to directly call back client methods in the OnConnected server hub event.
As your SignalR.connect() method instantly starts the connection, one can only attach listeners after connection is established. This way the cllient has no chance to get notified during connect.
So it would be nice to have the possibility to attach listeners before the connection is started.

Thanks and regards
Hannes

**Comment by HNeukermans** [comment]
Hey Spacepope, 

indeed. I already thought about something similar, but ...  

I think it is a better approach, to put your events callbacks inside a separate hub method, like Init() for example.

explanation: 
I would be careful putting business logic inside my OnConnected method, because, it is part of the Signalr framework, and we as developers, don't have full control over when the OnConnected method is called. 

There are cases where OnConnected method is called, while in fact a client reconnection is happening. It is explained it the official signalr documentation pages. It tells the scenario where a server does a reboot, so it goes temporary offline, meaning the client-server connection is lost. Then, when the server is back up, The OnConnected method is invoked, while in fact the client still has the previous client connection id.

**Comment by spacepope** [comment]
Hi,
thanks for the quick response.

From the architectural point of view i could agree with your paradigm to let the client actively get the needed data on initialization (so the client could react on errors etc...). 

Opposed to this the [Javscript Client API documentation](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client) states very clear to first get the hub proxy, then add the listeners and finally start the hub connection, precisely because its needed for OnConnected to be raised - and thats why you do it too and commented 
> // !!! important. We need to register at least one on function otherwise server callbacks will not work. 

;-)
but besides being a smart ass here, it would love to at least have the opportunity to go this way, so thanks for considering this for a future release..
👍
