### ISSUE TITLE
Update to Angular 4

### ISSUE THREAD

**Issue by LatinWarrior** [HNeukermans/ng2-signalr#57]
Would it be possible to update the application to the latest version of Angular and TypeScript? I am willing to create a branch and do the work if given permission. The application may also need a renaming from ng2-signalr to a more generic ng-signalr.

Thanks!

**Comment by HNeukermans** [comment]
Hi @LatinWarrior,

glad you like the library.
NG4 - Sure great idea. 
You can always submit pull request. I'll be happy to merge it in.

**Comment by HNeukermans** [comment]
verified. ng2-signalr works with latest @angular/cli projects that use ng4

**Comment by ritujav** [comment]
@HNeukermans  I want to know one thing in signalr.connection.js why are we sending args[0] as a response instead of sending whole args .
This is breaking my web as I am getting only first parameter only.

Please let me know if i am doing anything wrong.
![signalr](https://user-images.githubusercontent.com/33059570/42695941-6e43253e-86d4-11e8-92bc-2f5303786332.png)
