### ISSUE TITLE
.then is breaking

### ISSUE THREAD

**Issue by VasanJS** [HNeukermans/ng2-signalr#60]
I have been using ng2-signalr for the past few months without any issues, the version I was using was '2.0.3'. I was using the '.then' approach to establish the connection - `this._signalR.connect().then((c) => { });`
 Everything was fine till I deleted the node_modules folder and did 'NPM Install'. Post this, I started getting the error:

> Property 'then' does not exist on type 'ConnectInvocationResult'.

Kindly advice.

**Comment by markoj21** [comment]
The breaking change was introduced in version 2.0.5, version 2.0.4 still works. Workaround change your to "ng2-signalr": "2.0.4" and run npm install, this will reinstall the old version until this issue is fixed.

**Comment by HNeukermans** [comment]
@markoj21,

Ok markov. Thx for posting.
I will fix this asap.

**Comment by Jflima92** [comment]
@HNeukermans So what's the best way to connect now? using the connect, or the createConnection?
Thanks

**Comment by HNeukermans** [comment]
should be fixed in 2.0.6.

Best way to connect ??
as of 2.0.6 creating the connection is separated from starting it. This allows you to subscribe to connectionstatus changes before starting the connection. So the status observer will both receive connecting -> connected state changes nicely.
In 2.0.6 the connect() method has become a shortcut for writing createConnection().start().
